on: 
  push:
    branches:
    - Staging
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy Staging (testing)
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.irievibes.be
        server-dir: /home/deb109085/public_html/staging/
        username: web@irievibes.be
        password: ${{ secrets.ftp_password }}
        
